dzr_code/python/sbbs/sbbs/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from bbs1.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^accounts/login/$', 'bbs1.views.login', name='login'),
    url(r'^accounts/logout/$', 'bbs1.views.logout', name='logout'),
    url(r'^survey_statics/$', 'bbs1.views.survey_statics', name='survey_statics'),
    url(r'^$', index),
    url(r'^index/$', 'bbs1.views.index', name='index'),
    url(r'^index/(?P<survey_type>\d+)$', 'bbs1.views.survey', name='survey'),
    url(r'^index/(?P<survey_type>\d+)/post$', 'bbs1.views.post', name='post'),
    url(r'^index/(?P<survey_type>\d+)/submit_survey$', 'bbs1.views.submit_survey', name='submit_survey'),
    # url(r'^sbbs/', include('sbbs.foo.urls')),

    # chat
    url(r'^chat/(?P<room>\d+)/$', 'chat.views.index', name='chat_index'),
    url(r'^chat/(?P<room>\d+)/ajax/listen/\d+/$', 'chat.views.listen'),
    url(r'^chat/(?P<room>\d+)/ajax/getmsg/\d+/$', 'chat.views.getmsg'),
    # url(r'^chat/(?P<room>\d+)/ajax/postmsg/$', 'chat.views.postmsg'),
    url(r'^chat/(?P<room>\d+)/ajax/postmsg/$', 'chat.views.postmsg', name='postmsg'),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT },name="media")
)

dzr_code/python/sbbs/bbs1/models.py
# -*- coding: utf8 -*-

from django.db import models
from django import forms
from django.forms import ModelForm, Form

# Create your models here.

class Board(models.Model):
	survey_type = models.IntegerField(primary_key=True, verbose_name = "survey type")
	name        = models.CharField(max_length=50, unique=True)

	def __unicode__(self):
		return '/' + '/ ' + self.name

# Posts
class Post(models.Model):
	board     = models.ForeignKey(Board)

	level     = models.IntegerField(default=0) # depth in the tree
	rank      = models.IntegerField(default=0) # to determine rank within threads
	sticky    = models.BooleanField("Stickied", default=False) # to determine rank within boards
	locked    = models.BooleanField("Locked from replies", default=False) # whether to allow replies
	
	user_name = models.CharField("用户名", max_length=40, default="Anonymous")
	email     = models.EmailField("Email", max_length=256, blank=True)
	post_time = models.DateTimeField("Time", auto_now_add=True)
	subject   = models.CharField("Subject", max_length=40, blank=True)
	comment   = models.TextField("评论")

	def get_replies(self):
	    return self.replies.order_by('-rank', '-post_time')
	    
	def get_tree(self):
	    queue = [] # linear representation of the thread tree of replies
	    idx = 0 # where to insert children into the queue
	    level = 0 # how far to indent children (replies) in the queue

	    # initialize the queue with immediate children
	    for c in Post.objects.filter(reply=self).select_related('reply').order_by('-rank','-post_time').iterator():
	        queue.append((c, idx*INDENT_PIXELS))

	    # Populate the queue with descendants
	    for i in queue:
	        current = i[0] # fetch the current child (reply)
	        idx += 1 # increment the index

	        if Post.objects.filter(reply=current).count() == 0: # if the loop is not going to execute (current has no children)
	            if level > 0:
	                level -= 1 # decrement the level of indentation

	        else: # if the loop will execute (current has children)
	            level += 1 # increment the level of indentation
	            for j in Post.objects.filter(reply=current).select_related('reply').order_by('-rank','-post_time').reverse().iterator(): # sense of the order has to be reversed because the loop inserts in reverse order
	                queue.insert(idx, (j, level*INDENT_PIXELS))

	    return queue
	    
	def count_replies(self):
	    total = Post.objects.filter(reply=self.id).count()
	    for item in Post.objects.filter(reply=self.id).iterator():
	        if item.replies.count():
	            total += item.count_replies()
	    return total

	class Meta:
	    abstract = True


class TextPost(Post):
	reply = models.ForeignKey('self', related_name='replies', default=None, null=True, blank=True) # limit_choices_to={'board':self.board}
	root = models.ForeignKey('self', default=None, null=True, blank=True) # Original Post
	text = models.BooleanField(default=True, editable=False)

	def __get_tree(self, base, queue):
	    for post in TextPost.objects.order_by('-rank','-post_time').filter(reply=self.id).iterator():
	        queue.append((post, (post.level-base)*INDENT_PIXELS))
	        post.__get_tree(base, queue)
	    return queue
	        
	def get_tree(self):
	    return self.__get_tree(self.level, [])
	    
	def count_replies(self):
	    total = TextPost.objects.filter(reply=self.id).count()
	    for item in TextPost.objects.filter(reply=self.id).iterator():
	        if item.replies.count():
	            total += item.count_replies()
	    return total

	def get_highest_ranked_children(self, n=2):
	    return TextPost.objects.filter(reply=self.id).order_by('-rank', '-post_time')[:n]

class TextPostForm(ModelForm):
    # subject = forms.CharField(max_length=40, required=True)
    comment = forms.CharField(label = '评论', widget=forms.Textarea(attrs={'class':'textarea', 'rows':"5"}), max_length=1000000, required=True)
    # comment = forms.CharField(label = '评论', widget=forms.TextInput, max_length=1000000, required=True)
    class Meta:
        model = TextPost
        exclude = ('board', 'poster', 'reply', 'root', 'rank', 'level', 'sticky', 'locked', 'email','subject', 'user_name',)

class TextReplyForm(ModelForm):
    comment = forms.CharField(widget=forms.Textarea, max_length=1000000, required=True)
    class Meta:
        model = TextPost
        exclude = ('board', 'poster', 'reply', 'root', 'rank', 'level', 'sticky', 'locked', 'email', 'subject', 'user_name',)

# answer为：
# 	1: 完全不同意
# 	2: 基本不同意
# 	3: 有点不同意
# 	4: 有点同意同意
# 	5: 基本同意
# 	6: 完全同意
class QuestionSurvey(models.Model):
	user_name   = models.CharField("用户名", max_length=40, default="Anonymous")
	survey_type = models.IntegerField(verbose_name = "survey type")
	question_id = models.IntegerField(verbose_name = "question")
	answer      = models.IntegerField(verbose_name = "answer")

	
class QuestionConf(models.Model):
	def __str__(self):
		return "QuestionConf"

	class Meta:
		db_table = "questions"

	survey_type = models.IntegerField(verbose_name = "survey type")
	question_id = models.IntegerField(verbose_name = "question")
	describe    = models.CharField("describe", max_length=1000)


						
          	    

dzr_code/python/sbbs/sbbs/templates/head_nav.html
<div class="nav_welcome">{{user_name}} | <a href="{% url 'index' %}">首页</a> | <a href="{% url 'logout' %}">退出</a></div>

dzr_code/python/sbbs/sbbs/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- DW6 -->
<head>
<!-- Copyright 2005 Macromedia, Inc. All rights reserved. -->
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>群体极化调查</title>
<link rel="stylesheet" type="text/css" href="/static/my_css.css" />
</head>

<body>
	<!-- <div class="nav_welcome">{{user_name}}</div> -->
	{% include "head_nav.html" %}
	<div align='center'>
		<li><a href="{% url 'survey' survey_type=1 %}">调查一请进</a> </li>
		<li><a href="{% url 'survey' survey_type=2 %}">调查二请进</a> </li>
		<li><a href="{% url 'survey' survey_type=100 %}">调查xxx请进</a> </li>
		<li><a href="{% url 'survey_statics' %}">调查结果统计</a> </li>
	</div>
</body>

dzr_code/python/sbbs/sbbs/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- DW6 -->
<head>
<!-- Copyright 2005 Macromedia, Inc. All rights reserved. -->
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>群体极化调查</title>
<link rel="stylesheet" type="text/css" href="/static/my_css.css" />
</head>

<body>
	{% if error %}
        <p style="color: red;" align="center">用户名不存在或密码错误.</p>
    {% endif %}
	
	<form action="{% url 'login' %}" method="post">
	  {% csrf_token %}		
	  <div align="center">
	  	<p align="center">参与的昵称：<input type="text" name="user"></p>
	    <input type="submit" value="参与">
      </div>
	</form>
</body>

dzr_code/python/sbbs/sbbs/templates/posts.html
{% load mod %}
<div id="comments-list">
{% for post in posts %}
  {% if only_show_self_comment %}
    {%if post.user_name == user_name %}
    <div id="cid-{{post.id}}" class="comment" data-author="{{post.user_name}}" data-id="{{post.id}}">
        <div >
            <img style="display: inline;" src="/static/image/head{{forloop.counter|mod}}.png" alt="{{post.user_name}}" height="50" width="50">
           {{post.user_name}}: <pre >{{post.comment}}
----------------------------
<span class="date">发表于： {{post.post_time|date:"Y-m-d H:i:s"}} </span></pre>
        </div>
    </div>
    {% endif %}
  {% else %}
    <div id="cid-{{post.id}}" class="comment" data-author="{{post.user_name}}" data-id="{{post.id}}">
        <div >
            <img style="display: inline;" src="/static/image/head{{forloop.counter|mod}}.png" alt="{{post.user_name}}" height="50" width="50">
           {{post.user_name}}: <pre >{{post.comment}}
----------------------------
<span class="date">发表于： {{post.post_time|date:"Y-m-d H:i:s"}} </span></pre>
        </div>
    </div>
  {% endif %}
{% endfor %}
</div>

dzr_code/python/sbbs/sbbs/templates/question.html
<form action="{% url 'submit_survey' survey_type=type %}" method="post">
{% csrf_token %} 
<div>
	{% for question in questions %}
	<div class="question_detail">
		<span>问题{{question.question_id}}：{{question.describe}}</span></br>
		<input type="radio" name="answer{{question.question_id}}" value="1"  />完全不同意
		<input type="radio" name="answer{{question.question_id}}" value="2"  />基本不同意
		<input type="radio" name="answer{{question.question_id}}" value="3"  />有点不同意
		<input type="radio" name="answer{{question.question_id}}" value="4"  />有点同意
		<input type="radio" name="answer{{question.question_id}}" value="5"  />基本同意
		<input type="radio" name="answer{{question.question_id}}" value="6" checked="true"  />完全同意</br>
	</div>
	{% endfor %}
</div>
<div class="question_submit">
	{% if is_participated %}
		<span style="color:red">您已经参与过该调查了</span>
	{% else %}
		<input type="submit" value="提交" class="submit_new_thread" />
	{% endif %}
</div>
</form>

dzr_code/python/sbbs/sbbs/templates/question2.html
<form action="{% url 'submit_survey' survey_type=type %}" method="post">
{% csrf_token %} 
<div>
	{% for question in questions %}
	<div class="question_detail">
		<span>问题{{question.question_id}}：{{question.describe}}</span></br>
		<input type="radio" name="answer{{question.question_id}}" value="1"  />A1 一定选择A
		<input type="radio" name="answer{{question.question_id}}" value="2"  />A2 选择A
		<input type="radio" name="answer{{question.question_id}}" value="3"  />A3 可能选择A
		<input type="radio" name="answer{{question.question_id}}" value="4"  />B1 一定选择B
		<input type="radio" name="answer{{question.question_id}}" value="5"  />B2 选择B
		<input type="radio" name="answer{{question.question_id}}" value="6" checked="true"  />B3 可能选择B</br>
	</div>
	{% endfor %}
</div>
<div class="question_submit">
	{% if is_participated %}
		<span style="color:red">您已经参与过该调查了</span>
	{% else %}
		<input type="submit" value="提交" class="submit_new_thread" />
	{% endif %}
</div>
</form>

dzr_code/python/sbbs/sbbs/templates/question3.html
<form action="{% url 'submit_survey' survey_type=type %}" method="post">
{% csrf_token %} 
<div>
	{% for question in questions %}
	<div class="question_detail">
		<span>问题{{question.question_id}}：{{question.describe}}</span></br>
		<input type="radio" name="answer{{question.question_id}}" value="1"  />A1 一定选择A
		<input type="radio" name="answer{{question.question_id}}" value="2"  />A2 选择A
		<input type="radio" name="answer{{question.question_id}}" value="3"  />A3 可能选择A
		<input type="radio" name="answer{{question.question_id}}" value="4"  />B1 一定选择B
		<input type="radio" name="answer{{question.question_id}}" value="5"  />B2 选择B
		<input type="radio" name="answer{{question.question_id}}" value="6" checked="true"  />B3 可能选择B</br>
	</div>
	{% endfor %}
</div>
<div>
	请填写如下问卷，填写完毕请提交。
	<li>年龄</li>
	<li>性别</li>
	<li>职业</li>

</div>
<div class="question_submit">
	{% if is_participated %}
		<span style="color:red">您已经参与过该调查了</span>
	{% else %}
		<input type="submit" value="提交" class="submit_new_thread" />
	{% endif %}
</div>
</form>

dzr_code/python/sbbs/sbbs/templates/survey1.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--5秒钟后跳转到指定的页面-->
<meta http-equiv="refresh" content="5111;url=http://www.baidu.com" />
  <title>群体极化调查</title>
  <link rel='stylesheet' href="/static/site.css"/>
  <!-- <link rel='stylesheet' href="http://bm-cdn.b0.upaiyun.com/a411680/css/site.css?ver=a411680"/> -->
  <link rel="stylesheet" type="text/css" href="/static/my_css.css" />
  <link rel='shortcut icon' href='http://bm-cdn.b0.upaiyun.com/a411680/img/icons/favicon.png'/>
</head>

<body class="docs">
<!-- <div class="nav_welcome">{{user_name}}</div> -->
{% include "head_nav.html" %}
  <div class="container">
    <div id="main-content">
      
    <div class="highlight">
        <p class="" style="width:600px;">
            “kdkcn”对明天将要上市的手机进行产品预告
        </p>
    </div>
    <br/>
    <div class="highlight">
        <p class="" style="width:600px;">
          手机信息
          <img src="/static/image/image1.jpg" alt="XXX手机" title="XXX手机"  border="0"/>
        </p>
    </div>
    <div id="bm_comments" class="comments-holder"> 
      {% include "posts.html" %}
    </div>
  </br>
    <!-- <div > -->
    <form action="{% url 'post' survey_type=type %}" method="post" class="comment_rich_editor">
    {% csrf_token %} 
        <!-- <div class="input-guest-name">用户名：{{form.user_name}}</div> -->
        <div class="textarea">{{form.comment}}</div>
        <!-- <textarea id="id_comment" name="comment" style="display: none;"></textarea> -->
        <!-- <div id="comment-rich-editor" class="editor-content" contenteditable="true"></div> -->
        <div class="editor-footer">
            <input id="comment-submit" class="btn submit" value="发布评论" type="submit">

            <div class="clear"></div>
            
        </div>
        <div align='right'><a href="{% url 'survey' survey_type=100 %}" class="btn submit">结束</a></div>
    </form>
    <!-- </div> -->
    <div class="clear"></div>

    </div>
</br>
    <div class="clear"></div>
  </div>

  

</body>
</html>

dzr_code/python/sbbs/sbbs/templates/survey100.html
<!DOCTYPE html>
<html class="no-js"> 
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>群体极化调查</title>
  <link rel='stylesheet' href="/static/site.css"/>
  <!-- <link rel='stylesheet' href="http://bm-cdn.b0.upaiyun.com/a411680/css/site.css?ver=a411680"/> -->
  <link rel="stylesheet" type="text/css" href="/static/my_css.css" />
  <link rel='shortcut icon' href='http://bm-cdn.b0.upaiyun.com/a411680/img/icons/favicon.png'/>
</head>

<body class="docs">
<!-- <div class="nav_welcome">{{user_name}}</div> -->
{% include "head_nav.html" %}
  <div class="container">
    <div id="main-content">
      
    <div class="highlight">
        <p class="" style="width:600px;">
            团购信息。某产品发布。。。。
        </p>
    </div>
    <br/>
    <!-- <div class="highlight">
        <p class="" style="width:600px;">
          手机信息
          <img src="/static/image/image1.jpg" alt="XXX手机" title="XXX手机"  border="0"/>
        </p>
    </div> -->
    
  </br>
    
    <div class="clear"></div>

    <div class="question">
        <p>通过上述讨论，请您再次选择：：A团购 或者B不团购</p>
        {% include "question2.html" %}
    </div>

    </div>
</br>
    <div class="clear"></div>
  </div>

  

</body>
</html>

dzr_code/python/sbbs/sbbs/templates/survey101.html
<!DOCTYPE html>
<html class="no-js"> 
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>群体极化调查</title>
  <link rel='stylesheet' href="/static/site.css"/>
  <!-- <link rel='stylesheet' href="http://bm-cdn.b0.upaiyun.com/a411680/css/site.css?ver=a411680"/> -->
  <link rel="stylesheet" type="text/css" href="/static/my_css.css" />
  <link rel='shortcut icon' href='http://bm-cdn.b0.upaiyun.com/a411680/img/icons/favicon.png'/>
</head>

<body class="docs">
<!-- <div class="nav_welcome">{{user_name}}</div> -->
{% include "head_nav.html" %}
  <div class="container">
    <div id="main-content">
      
    <div class="highlight">
        <p class="" style="width:600px;">
            团购信息。某产品发布。。。。
        </p>
    </div>
    <br/>
    <!-- <div class="highlight">
        <p class="" style="width:600px;">
          手机信息
          <img src="/static/image/image1.jpg" alt="XXX手机" title="XXX手机"  border="0"/>
        </p>
    </div> -->
    
  </br>
    
    <div class="clear"></div>

    <div class="question">
        <p>通过上述讨论，请您再次选择：A团购 或者B不团购</p>
        {% include "question3.html" %}
    </div>

    </div>
</br>
    <div class="clear"></div>
  </div>

  

</body>
</html>

dzr_code/python/sbbs/sbbs/templates/survey2.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>群体极化调查</title>
  <link rel='stylesheet' href="/static/site.css"/>
  <!-- <link rel='stylesheet' href="http://bm-cdn.b0.upaiyun.com/a411680/css/site.css?ver=a411680"/> -->
  <link rel="stylesheet" type="text/css" href="/static/my_css.css" />
  <link rel='shortcut icon' href='http://bm-cdn.b0.upaiyun.com/a411680/img/icons/favicon.png'/>
</head>

<body class="docs">
<!-- <div class="nav_welcome">{{user_name}}</div> -->
{% include "head_nav.html" %}
  <div class="container">
    <div id="main-content">
      
    <div class="highlight">
        <p class="" style="width:600px;">
            “kdkcn”对明天将要上市的手机进行产品预告
        </p>
    </div>
    <br/>
    <div class="highlight">
        <p class="" style="width:600px;">
          手机信息
          <img src="/static/image/image1.jpg" alt="XXX手机" title="XXX手机"  border="0"/>
        </p>
    </div>
    <div id="bm_comments" class="comments-holder"> 
      {% include "posts.html" %}
    </div>
  </br>
    <!-- <div > -->
    <!-- <form action="{% url 'post' survey_type=type %}" method="post" class="comment_rich_editor">
    {% csrf_token %} 
        <div class="textarea">{{form.comment}}</div>
        <div class="editor-footer">
            <input id="comment-submit" class="btn submit" value="发布评论" type="submit">
            <div class="clear"></div>
        </div>
    </form> -->
    <!-- </div> -->
    <div class="clear"></div>

    <div class="question">
        <p>通过对以上评论的阅读，请你完成以下的问题</p>
        {% include "question.html" %}
    </div>

    </div>
</br>
    <div class="clear"></div>
  </div>

  

</body>
</html>
 

dzr_code/python/sbbs/sbbs/templates/survey_statics.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- DW6 -->
<head>
<!-- Copyright 2005 Macromedia, Inc. All rights reserved. -->
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<title>群体极化调查</title>
<link rel="stylesheet" type="text/css" href="/static/my_css.css" />
</head>

<body>
{% include "head_nav.html" %}
{% for survey_type, statics in board_dict.items %}
<div class="statics">
<p>调查{{survey_type}}统计如下：</p>
	
	{% for question_id, static in statics %}
		<div class="statics_head"><p>选择问题{{question_id}}的答案分布如下：</p></div>
		<div class="statics_detail" >
			完全不同意: <span>{{static.answer1}}</span> | 基本不同意: <span>{{static.answer2}}</span> | 有点不同意: <span>{{static.answer3}}</span> | 有点同意: <span>{{static.answer4}}</span> | 基本同意: <span>{{static.answer5}}</span> | 完全同意: <span>{{static.answer6}}</span>
		</div>
	{% endfor %}
</div>
{% endfor %}
</body>

dzr_code/python/sbbs/sbbs/templates/thank_you.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- DW6 -->
<head>
<!-- Copyright 2005 Macromedia, Inc. All rights reserved. -->
<meta http-equiv="Content-Type" content="text/html; charset=utf8" />
<link rel="stylesheet" type="text/css" href="/static/my_css.css" />
<title>群体极化调查</title>
</head>

<body>
	{% include "head_nav.html" %}
	<div align='center'>
		<p>调查提交成功，谢谢您的参与！</p>
		<a href="{% url 'survey_statics' %}">调查结果统计</a>
	</div>
</body>